query ($uuid: ID!) {
  question (uuid: $uuid) {
    id
    uuid
    instruction
    support
    body
    alternatives {
      correct
      text
    }
    explanation
    references
    source
    authorshipYear
    difficulty
    checkType
    bloomTaxonomy
    subject {
      name
      subject {
        name
        axis {
          name
        }
        category {
          name
        }
      }
    }
    status
    reviewer {
      id
      name
    }
    reviewFeedbacks {
      id
      status
      comment
      user {
        name
        avatarUrl
      }
    }
    updatedAt
    createdAt
  }
}