export const AUTHENTICATION_LOAD = "@auth/AUTHENTICATION_LOAD";
export const AUTHENTICATION_LOAD_FAILURE = "@auth/AUTHENTICATION_LOAD_FAILURE";

export const AUTHENTICATION_REQUEST = "@auth/AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS = "@auth/AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "@auth/AUTHENTICATION_FAILURE";

export const LOGOUT = "@auth/LOGOUT";
